### ISSUE TITLE
Error: Invalid or corrupt jarfile

### ISSUE THREAD

**Issue by rameshnatesan** [Drill4J/java-agent#90]
In Windows 10, when I extract "agent-mingwX64-0.7.0.zip" and ran  **java -jar drillRuntime.jar.**, it says 
`Error: Invalid or corrupt jarfile`
Please help.

**Comment by Mazel-Tovr** [comment]
Hello @rameshnatesan, sorry for long response time.
We are using a java native agent, so you need to specify path to .dll file.
%DISTR% - path to the unzipped folder. 
java -agentpath:%DISTR%/drill_agent.dll=drillInstallationDir=%DISTR%/,adminAddress=localhost:8090,agentId=agentId,buildVersion=0.1.0,logLevel=TRACE -jar your_application.jar
